# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: HAN KUG
title: Junior Developer
email: hankug12@gmail.com
website: https://github.com/hankug1234

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: null
github_username:  hankug1234
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: null
linkedin_username: hankug1234
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: null
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://github.com/hankug1234
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  제 이름은 한국 입니다. 저는 1998년 생이며 현재 육군 중위로 전역후 IT취업 준비를 하고 있는 한 주제에 깊게 파고드는 끈기와 성실함이 있는 개발자 입니다.
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  usable languages : <mark>Java</mark>, <mark>python</mark>, <mark>c++/c</mark>, <mark>Java Scripte</mark>, <mark>HTML/CSS</mark> <br/>
  usable frameworks: <mark>Java Spring</mark><br/>
  usable databases : <mark>MYSQL</mark><br/>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My Projects
        link: https://github.com/hankug1234
        # link_text: Project Website
        additional_links:
          - title:  hankug projects
            icon: fab fa-github
            url: https://github.com/hankug1234
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is my developing history log, I want to make more exciting and useful projects
        description: | # this will include new lines to allow paragraphs
          -comming soon



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: null
        link: null
        # link_text: boringcompany.com
        sub_title: null
        caption: null
        quote: >
          comming soon

        description: | # this will include new lines to allow paragraphs
            -

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gachon University
        caption: 2016.03.01 - 2020.02.09
        sub_title: Mathematical finance <br/><span style="text-align:cneter">&</span><br/> software engineering
        quote: >
          I have dual major in methematical financce and software engineering
        description: | # this will include new lines to allow paragraphs
          저는 금융수학 분야에서 금융공학 과 선형대수, 대수학, 해석학, 미분적분학, 미분방정식, 위상수학, 확률론, 수치해석 등을 공부하였으며<br/>
          소프트웨어 공학 분야에서 데이터 베이스, 운영체제, 소프트웨어 공학, 네트워크, 컴퓨터 구조 등의 컴퓨터 과학 전반의 지식을 공부 하였습니다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      저의 취미는 영화감상 및 독서 입니다 주말에는 주로 아래와 같은 활동으로 시간을 보냅니다.
      - 독서 : 요즘 범주론 데이터 중심 어플리케이션 설계 책을 읽고 있습니다.
      - 운동 : 간단한 조깅과 턱걸이를 주로 합니다.
      - 영화 : 느와르 장르를 좋아 합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
